// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqyivfvhsptwvihlhnwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeWl2ZnZoc3B0d3ZpaGxobnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTk1MDksImV4cCI6MjA3NDUzNTUwOX0.Fh1BQkyiGJEQYfyjl9IGYKejO9JsHhrUJhb9IRrfI1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});