// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itjvvjzfqgnixqbxqhgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0anZ2anpmcWduaXhxYnhxaGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTE5MzksImV4cCI6MjA3Mzk2NzkzOX0.MVOOy2AePOgwV0YCWZzbfLi7vn4W3SV_XmtzzGR0O5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});